version: '3'

services:
  app:
    container_name: 'duplo-order-manager'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: postgres_db
      REDIS_HOST: redis
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres_db
      - redis
    networks:
      myapp_net:

  postgres_db:
    image: bitnami/postgresql:15
    container_name: 'duplo_postgres_db'
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    networks:
      myapp_net:
  redis:
    image: 'bitnami/redis:7.2'
    container_name: 'duplo_redis'
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - 'redis_data:/bitnami/redis/data'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_IO_THREADS: 4
      REDIS_IO_THREADS_DO_READS: yes
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    networks:
      myapp_net:

volumes:
  postgres_data:
  redis_data:

networks:
  myapp_net:
